name: client
description: "PixelChat - корпоративный мессенджер"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  
  # Network
  dio: ^5.3.3
  web_socket_channel: ^2.4.0
  
  # State management
  provider: ^6.1.1
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Environment variables
  flutter_dotenv: ^5.1.0
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.2.1

  elliptic: ^0.3.0
  encrypt: ^5.0.0
  cryptography: ^2.7.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  
  # Ассеты - правильно, без дефисов
  assets:
    - .env